import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  infoButton: {
    width: "35%",
    height: 70,
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
    marginTop: -5,
    elevation: 6,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    borderWidth: 3.3,
    borderColor: "#F6F6F6",
    gap: 4,

  },
  infoButtonText: {
    fontSize: 17,
    color: "#F6F6F6",
    marginTop: -5,
    fontFamily: "Nunito_700Bold",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "#00000080",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  modalContent: {
    width: "85%",
    backgroundColor: "#F6F6F6",
    borderRadius: 20,
    paddingVertical: 28,
    paddingHorizontal: 25,
    alignItems: "center",
    position: "relative",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  closeIconButton: {
    position: "absolute",
    top: 12,
    right: 12,
    padding: 5,
    zIndex: 1,
  },
  modalTitle: {
    fontSize: 24,
    fontFamily: "Poppins_700Bold",
    marginBottom: 15,
    textAlign: "center",
    paddingHorizontal: 10,
  },
  modalText: {
    fontSize: 18,
    color: "#696969",
    textAlign: "center",
    lineHeight: 25,
    width: "100%",
    fontFamily: "Poppins_600MediumBold",
  },
});